name: pr
on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:pr-${{ github.event.pull_request.number }}
    - name: Create a cluster
      uses: AbsaOSS/k3d-action@v1.4.0
      with:
        cluster-name: test
        args: >-
          --config k3d.yaml
    - name: Deploy the app
      run: |
        cd kustomize/overlays/preview
        kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo=${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:pr-${{ github.event.pull_request.number }}
        kustomize build | kubectl apply --filename -
        kubectl rollout status deployment github-actions-demo
    - name: Test
      run: |
        kubectl run test --image alpine -i --restart Never -- sh -c "apk add --update curl && curl github-actions-demo"
